### ISSUE TITLE
Dialog window does not show up Grid

### ISSUE THREAD

**Issue by vaithu** [holon-platform/holon-vaadin-flow#85]
PropertyListing listing = PropertyListing.builder(SUBJECT)
                .items(PropertyBox.builder(SUBJECT).set(ID, 1L).set(NAME, "One").build()).build();

        add(Components.dialog.message().withComponent(listing).open());

This does not show the Grid in the dialog. But the below shows the Grid
Dialog dialog = new Dialog();
        dialog.add(listing.getComponent());
        dialog.open();
        add(dialog);

**Comment by axholo** [comment]
The problem is originated from the Vaadin Dialog layout, which does not properly renders the grid  component in its content when has not a defined size.

As a workaround, you can provide a width for the dialog and set the PropertyListing component as full width:
```
PropertyListing listing = PropertyListing.builder(SUBJECT).fullWidth()
.items(PropertyBox.builder(SUBJECT).set(ID, 1L).set(NAME, "One").build()).build();
```
`Components.dialog.message().withComponent(listing).width("300px").open();`

Furthermore, you don't need to `add `the dialog to a parent component, since the `open()` method already adds the dialog to the UI.
